# Generated by Django 4.2.7 on 2024-04-04 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('desafiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafiante', to='principal.jogador')),
                ('detentor_atual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detentor_atual', to='principal.jogador')),
                ('vencedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vencedor', to='principal.jogador')),
            ],
        ),
    ]
