# Generated by Django 4.2.7 on 2024-04-04 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='vencedor',
        ),
        migrations.AddField(
            model_name='partida',
            name='penaltis_desafiante',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partida',
            name='penaltis_detentor_atual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partida',
            name='placar_desafiante',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partida',
            name='placar_detentor_atual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partida',
            name='desafiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_desafiante', to='principal.jogador'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='detentor_atual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_detentor', to='principal.jogador'),
        ),
    ]
