# Generated by Django 4.2.7 on 2024-04-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_remove_partida_vencedor_partida_penaltis_desafiante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='vencedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='desafiante',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='partida',
            name='detentor_atual',
            field=models.CharField(max_length=100),
        ),
    ]
