# Generated by Django 4.2.7 on 2024-04-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_remove_partida_vencedor_alter_partida_desafiante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='imagem_url',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
    ]
