# Generated by Django 5.1.1 on 2024-09-28 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_alter_jogador_imagem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='partida',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='partida',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
