# Generated by Django 5.1.1 on 2024-09-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_partida_created_at_alter_partida_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='partida',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
